CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME varchar(255) NOT NULL,
    EMAIL varchar(255) UNIQUE NOT NULL,
    PICTURE varchar(512),
    CREATED_AT datetime2 NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
);

CREATE TABLE CD_SESSION_TYPE (
    SESSION_TYPE_CD varchar(64) PRIMARY KEY,
    CREATED_AT datetime2  NOT NULL,
    ARCHIVED bit DEFAULT 0
);

CREATE TABLE SESSION(
    SESSION_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    SESSION_TYPE_CD varchar(64) NOT NULL,
    TOKEN varchar(512) NOT NULL,
    SESSION_START datetime2 NOT NULL,
    SESSION_STOP datetime2 NOT NULL,
    CREATED_AT datetime2  NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
    FOREIGN KEY (SESSION_TYPE_CD) REFERENCES CD_SESSION_TYPE(SESSION_TYPE_CD),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
);

CREATE TABLE USER_DETAILS (
    USER_DETAILS_ID INTEGER NOT NULL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    GIVEN_NAME varchar(255),
    FAMILY_NAME varchar(255),
    LOCALE varchar(255),
    EMAIL_VERIFIED bit,
    HOSTED_DOMAIN varchar(255),
    PRN varchar(255),
    SCOPE varchar(255),
    CREATED_AT datetime2 NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
);