CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    DISPLAY_NAME varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
);

CREATE TABLE CD_SESSION_TYPE (
    SESSION_TYPE_CD varchar(64) PRIMARY KEY,
    CREATED_AT datetime2  NOT NULL,
    ARCHIVED bit DEFAULT 0
);

CREATE TABLE SESSION(
    SESSION_ID INTEGER PRIMARY KEY,
    SESSION_TYPE_CD varchar(64) NOT NULL,
    TOKEN varchar(255) NOT NULL,
    SESSIONT_START datetime2 NOT NULL,
    SESSION_STOP datetime2 NOT NULL,
    CREATED_AT datetime2  NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
    FOREIGN KEY (SESSION_TYPE_CD) REFERENCES CD_SESSION_TYPE(SESSION_TYPE_CD),
);

CREATE TABLE USER_DETAILS (
    USERS_ID INTEGER NOT NULL PRIMARY KEY,
    GIVEN_NAME varchar(255),
    FAMILY_NAME varchar(255),
    LOCALE varchar(255),
    EMAIL_VERIFIED bit,
    HOSTED_DOMAIN varchar(255),
    PRN varchar(255),
    SCOPE varchar(255) NOT NULL,
    MODIFIED_AT datetime2,
    ARCHIVED bit DEFAULT 0,
    FOREIGN KEY (USERS_ID) REFERENCES USERS(USER_ID),
);